### ISSUE TITLE
Incomplete response download

### ISSUE THREAD

**Issue by Mental-Inferno** [ubccapico/canvas-discussion#11]
When downloading discussions, if the student has a blank line (has pressed the enter key) in the middle of their response, the excel spreadsheet only contains the top half of the response. 

For example, if the response was:

"Red is my favourite colour
It reminds me of apples"

The excel spreadsheet would only contain: <p>Red is my favourite colour</p>

**Comment by justin0022** [comment]
Oh thanks for this, I'll look into it. I expect it's due to this line: https://github.com/ubccapico/canvas-discussion/blob/master/writeToCSV.js#L8

**Comment by justin0022** [comment]
Hi @Mental-Inferno, I just tested this, and it worked correctly for me. This was what was in my spreadsheet: 

```
<p><span>Red is my favourite colour</span><br><span>It reminds me of apples</span></p>
<p><span>Testing a script</span></p>
```

If you copy the contents of the cell, and paste it somewhere else, I think you'll see the next line as well.

**Comment by Mental-Inferno** [comment]
This is what is coming up for me when I run a test response
![image](https://user-images.githubusercontent.com/59522230/98575345-14cf6e80-2287-11eb-9469-c268187a7813.png)
The letters are separated via an enter

**Comment by Mental-Inferno** [comment]
It turns out that the enter works when viewing the .csv file with Libre Office
