### ISSUE TITLE
Spaces being replaced with Â 

### ISSUE THREAD

**Issue by Mental-Inferno** [ubccapico/canvas-discussion#12]
When student responses contain more than one continuous space, some of the spaces are replaced with Â.

Example response:
![image](https://user-images.githubusercontent.com/59522230/98425555-89c25e80-2063-11eb-88ef-c19986ec85be.png)

will give an output: <p>Testing1 Testing2Â  Testing3Â Â  Testing4Â Â Â  Testing5Â Â Â Â  Testing6Â Â Â Â Â  Testing7Â Â Â Â Â Â  Testing8Â Â Â Â Â Â Â  Testing9Â Â Â Â Â Â Â Â Â  Testing10Â Â Â Â Â Â Â Â Â  .</p>

Is this just part of the program?

**Comment by justin0022** [comment]
Hmm, I'll look into this too. I think it's again due to this line: https://github.com/ubccapico/canvas-discussion/blob/master/writeToCSV.js#L8

It's a bit tricky to put comments into a CSV column, because if the comments have a comma in them, it can break the delimitation.

**Comment by Mental-Inferno** [comment]
https://stackoverflow.com/questions/4617935/is-there-a-way-to-include-commas-in-csv-columns-without-breaking-the-formatting

It seems that enclosing the fields in quotes would allow for commas to be included in the cell content without delimination

**Comment by justin0022** [comment]
Hmm ya, my code as written actually does support having commas in the comments, as this comment shows: 
```
"<p>Any questions about the hackathon that we haven't answered, ask here!</p>"
```

**Comment by justin0022** [comment]
For the weird characters that you see, I don't actually see that in my results: 
I typed this in the discussions: `testing testing    testing          test` 
And got this in the downloaded result: `"<p>testing testing    testing          test</p>"`

**Comment by justin0022** [comment]
I'm viewing the downloaded CSV in VSCode - perhaps there could be different ways that different programs render the CSVs?

**Comment by Mental-Inferno** [comment]
I'm viewing the .csv in excel, perhaps I'll try a different software and let you know

**Comment by Mental-Inferno** [comment]
The strange character still appear when the .csv file is opened with Libre Office. The lines separated by enters show up now however the strange characters created by over 5 consecutive spaces still appear

**Comment by Mental-Inferno** [comment]
When opening in a text editor, the special characters don't appear. I'll edit the code to collect only the data I need and access via a text editor. Thanks for all the support.

**Comment by justin0022** [comment]
No problem!
