### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by Mental-Inferno** [ubccapico/canvas-discussion#9]
![image](https://user-images.githubusercontent.com/59522230/98397116-d5a5e100-202c-11eb-8a2a-662b7bb1aa21.png)
Perhaps an option to install this registry should be added

**Comment by justin0022** [comment]
Hmm... I just tried installing it and it worked for me. You're seeing this on `npm install`? What version of npm/node are you running?

**Comment by Mental-Inferno** [comment]
node.js version: 14.15.0

npm version: 6.14.8

**Comment by justin0022** [comment]
I updated the dependencies - could you try `git pull` then `npm install` one more time?

**Comment by Mental-Inferno** [comment]
There is a warning but it seems to have worked ...
![image](https://user-images.githubusercontent.com/59522230/98399071-e3109a80-202f-11eb-8119-9cd9cabb4a8f.png)

**Comment by Mental-Inferno** [comment]
Is this what it's supposed to output?

**Comment by justin0022** [comment]
Okay great, that warning is not important. Looks like you should be good to go now!

**Comment by Mental-Inferno** [comment]
Thanks!
